version: '3.3'

services:
    database:
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: 'Krankenhaus9'
            MYSQL_DATABASE: 'ravemap'
            MYSQL_USER: 'symfony'
            MYSQL_PASSWORD: 'symfony_ravemap'
        ports:
            - '4406:3306'
        volumes:
            - type: volume
              source: database_data
              target: /var/lib/mysql
              volume:
                nocopy: true
    php:
        build:
            context: ./docker/php
        command: sh /post-install/run.sh
        environment:
            APP_ENV: 'dev'
            APP_SECRET: '8d0d1677a02b1bd09326fc3403bdfb0f'
            DATABASE_URL: 'mysql://symfony:symfony_ravemap@database:3306/ravemap?serverVersion=mariadb-10.6.4'
        ports:
            - '9090:9000'
            - '1234:1234'
        volumes:
            - type: volume
              source: web_data
              target: /var/www/symfony
              volume:
                nocopy: true
            - './docker/php/scripts:/post-install'
    nginx:
        image: nginx:stable-alpine
        environment:
            APP_ENV: 'dev'
            APP_SECRET: '8d0d1677a02b1bd09326fc3403bdfb0f'
            DATABASE_URL: 'mysql://symfony:symfony_ravemap@database:3306/ravemap?serverVersion=mariadb-10.6.4'
        ports:
            - '8080:80'
        depends_on:
            - php
        volumes:
            - './docker/nginx:/etc/nginx/conf.d'
            - type: volume
              source: web_data
              target: /var/www/symfony
              volume:
                nocopy: true

volumes:
    database_data:
    web_data: