endroid_qr_code:
    writer: 'png'
    size: 200
    margin: 0
    foreground_color: { r: 0, g: 0, b: 0 }
    background_color: { r: 255, g: 255, b: 255 }
    error_correction_level: high # low, medium, quartile or high
    logo_path: '%kernel.project_dir%/public/img/logo/logo_small_icon_only_inverted.png'
    logo_width: 100
    logo_height: 100
    encoding: UTF-8
    validate_result: false # checks if the result is readable
    writer_options:
        exclude_xml_declaration: true
