homepage:
  path: /
  controller: App\Controller\DefaultController::indexAction

ravemap_map_image_event:
  path: /mapimage/{eventId}.png
  controller: App\Controller\MapImageController::eventMapImageAction

controllers:
  resource: ../../src/Controller/Main
  type: annotation
  prefix: /{_locale}
  requirements:
    _locale: '[a-z]{2}'
  defaults:
    _locale: '%locale%'


api_controllers:
  prefix: /api
  resource: ../../src/Controller/Api
  type: annotation
